@katyhuff edits implemented
arfc/msbr-reproc pull request #18
Opened 2018-08-25 08:02 UTC by andrewryh

This PR resolves issues #5 #8 #9 #10 #12 #13 #14 #16 #17

2018-08-25 20:52 UTC, katyhuff requested changes
Thanks for making these changes. See comments for some minor grammatical issues.

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +designs\footnote{Examples include both liquid-fueled and solid-fueled molten
In the abstract, this should be a sentence rather than a footnote.

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +Nowadays climate change pushes humankind in search new ways to generate
"Nowadays" is too colloquial.

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +carbon-free, reliable, nonintermittent base load power. That is reason why
nonintermittent should be deleted.

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +interest in advanced nuclear energy and, particularly \glspl{MSR} has resurged,
delete the comma between "and" and "particularly"

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +carbon-free, reliable, nonintermittent base load power. That is reason why
"That is reason why" should be "Thus,"

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +develop these \gls{MSR} concepts researchers need tools for analyzing liquid
comma after concepts.

tools -> simulation tools

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +introduces a Python script, SaltProc, which couples with the Monte Carlo code,
script should be "package"

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +isotopic composition of an irradiated fuel salt. SaltProc capabilities was
get rid of irradiated. 
Perhaps "changing isotopic composition of MSR fuel salt"


Also "SaltProc capabilities were demonstrated"

2018-08-25 20:52 UTC, katyhuff commented on abstract.tex
> +demonstrated for full-core high-fidelity model of the commercial \gls{MSBR}
"for a full-core, high-fidelity model"

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +and good flow and heat transfer properties \cite{robertson_conceptual_1971}. In
"good" is still vague. But ok.

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +misrepresent the two-region breeder reactor concept. The unit-cell or one-region
misrepresents

2018-08-25 20:52 UTC, katyhuff commented on results.tex
> +fuel salt change insignificantly after approximately 2500 days of operation.
the fuel salt

2018-08-25 20:52 UTC, katyhuff commented on results.tex
> +Particularly, $^{233}$U number density fluctuates less than 0.8\% in the time
"the ${233}U$"

2018-08-25 20:52 UTC, katyhuff commented on results.tex
> +because allows achieve longer core lifetime.
"because allows achieve longer" should be "and enables a"

2018-08-25 20:52 UTC, katyhuff commented on methods.tex
> +Liquid-fueled systems ability to continuously remove fission products and add
"Liquid-fueled systems ability" should be "The ability of liquid-fueled systems".

2018-08-25 20:52 UTC, katyhuff commented on methods.tex
> +Introduced in this work Python-package, SaltProc, takes into account online
"Introduced in this work Python-package, SaltProc," should be "The python package introduced in this work, Salt Proc"

2018-08-25 20:52 UTC, katyhuff commented on methods.tex
> +separations and feeds using SERPENT 2 continuous-energy Monte Carlo neutron
"using SERPENT 2" should be "using the SERPENT 2"

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +from a deterministic transport calculation. Approaches listed in references
"Approaches" should be "Meanwhile, approaches"

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +material moves to and from the core at specific time steps (batch) or
"material moves to and from the core at specific time steps (batch) or continuously"
should be 
"material moves to and from the core continuously or at specific time steps (batch-wise)"

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +continuously. In batch-wise approach the burn-up simulation stops at a given
"In batch-wise approach the" should be "In the batch-wise approach, the "

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +time and restart with a new liquid fuel composition (after removal of discarded
"restart" should be "restarts"

2018-08-25 20:52 UTC, katyhuff commented on introduction.tex
> +and current work employ a batch-wise approach.
"and current work" should be "as well as the current work"

2018-08-26 07:55 UTC, andrewryh commented
@katyhuff Thanks for the comments. I've fixed it.

2018-08-26 13:27 UTC, merged