PR after group mates comments
arfc/msbr-reproc pull request #24
Opened 2018-09-06 12:49 UTC by andrewryh

This PR resolves issues #21 #20 #19 #22 #23

2018-09-06 12:55 UTC, katyhuff commented on results.tex
> +  \includegraphics[scale=•]{•}=\textwidth]{major_isotopes_adens.png}
This change causes a build error for me.  Seems like some kind of typo

2018-09-06 13:08 UTC, andrewryh commented
OMG, that is the shame.
Broke it occasionally when switched between windows using Alt+Tab

2018-09-06 13:38 UTC, katyhuff requested changes
minor comments here.  looking great! (I have a few more edits, but I'll submit those changes myself as a pr)

2018-09-06 13:38 UTC, katyhuff commented on methods.tex
> +Saltproc datasets are time-series, meaning that every value is recorded every
I don't think I like hyphenating time series. Perhaps "SaltProc records every value every timestep. The resulting time series datasets produced by SaltProc are listed below.... "

2018-09-06 13:38 UTC, katyhuff commented on results.tex
> +contained significant amount of $^{235}$U ($\approx10^{-5}$ atom/b-cm), $^{239}$Pu
delete "amount of"

2018-09-06 13:38 UTC, katyhuff commented on results.tex
> +but notable for thermal neutrons. These neutron flux radial distributions is in
"These... distributions... are"

2018-09-06 13:38 UTC, katyhuff commented on results.tex
> +generated in zone I with exception to the majority of $^{233}$Th that is
with exception to --> except

2018-09-06 13:38 UTC, katyhuff commented on results.tex
> +The effective multiplication factor can be expressed using next formula:
"using the following formula:"

2018-09-06 14:18 UTC, katyhuff commented on methods.tex
> +Saltproc datasets are time-series, meaning that every value is recorded every
see https://github.com/andrewryh/msbr-reproc/pull/3

2018-09-06 14:18 UTC, katyhuff commented on results.tex
> +contained significant amount of $^{235}$U ($\approx10^{-5}$ atom/b-cm), $^{239}$Pu
https://github.com/andrewryh/msbr-reproc/pull/3

2018-09-06 14:18 UTC, katyhuff commented on results.tex
> +but notable for thermal neutrons. These neutron flux radial distributions is in
https://github.com/andrewryh/msbr-reproc/pull/3

2018-09-06 14:18 UTC, katyhuff commented on results.tex
> +generated in zone I with exception to the majority of $^{233}$Th that is
see https://github.com/andrewryh/msbr-reproc/pull/3

2018-09-06 14:18 UTC, katyhuff commented on results.tex
> +The effective multiplication factor can be expressed using next formula:
see https://github.com/andrewryh/msbr-reproc/pull/3

2018-09-06 14:21 UTC, katyhuff commented
Once see https://github.com/andrewryh/msbr-reproc/pull/3 is merged into this PR, all of my comments will have been handled and I will change review to 'approve'

2018-09-06 19:39 UTC, anshchaube requested changes

2018-09-06 19:39 UTC, achubbz commented on introduction.tex
> +$^{232}$Th is almost instantly\footnote{\space $^{232}$Th transmutes into
$^{232}$Th is almost instantly\footnote{\space $^{232}$Th transmuted into

2018-09-10 19:37 UTC, katyhuff commented
@andrewryh  -- please don't add more to this PR. New issues can be handled in separate PRs. Please complete this PR approval by merging  https://github.com/andrewryh/msbr-reproc/pull/3 . Then, we can merge this PR and it will be safe to move on to other issues.

2018-09-10 20:10 UTC, merged